---
version: 2.1

# Whenever the versions here are increased, also increment the versions of the build caches
executors:
  golang:
    docker:
      - image: circleci/golang:1.14-node

  golangci:
    docker:
      - image: golangci/golangci-lint:v1.21.0

jobs:
  build:
    executor: golang

    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-build-cache
      - run: make build
      - save_cache:
          key: v3-build-cache
          paths:
            - go/pkg
            - ~/.cache/go-build

  test:
    executor: golang

    steps:
      - checkout
      # Reuse build cache if available
      - restore_cache:
          keys:
            - v3-build-cache
      - run: make test

  crossbuild:
    executor: golang

    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-crossbuild-cache
      - run: cd ..; GO111MODULE=on go get github.com/goreleaser/goreleaser@v0.131.1
      - run: git reset --hard
      - run: make crossbuild
      - run: mkdir artifacts
      - run: mv dist/*.tar.gz dist/checksums.txt artifacts
      - store_artifacts:
          path: ./artifacts
      - save_cache:
          key: v4-crossbuild-cache
          paths:
            - go/pkg
            - ~/.cache/go-build

  publish_release:
    executor: golang

    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-crossbuild-cache
      - run: cd ..; GO111MODULE=on go get github.com/goreleaser/goreleaser@v0.131.1
      - run: git reset --hard
      - run: make release 

  check_repo_consistency:
    executor: golang
    
    steps:
      - checkout
    # - run: go get github.com/rakyll/statik@v0.1.7
    # - run: make clean
    # - run: make generated
    # - run: bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make generated' and commit again ; exit 1 )"
      - run: make fmt
      - run: bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make fmt' and commit again ; exit 1 )"
      - run: make update_internal_packages
      - run: bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'make update_internal_packages' and commit again ; exit 1 )"
      - run: go mod tidy
      - run: bash -c "[[ `(git diff ; git add -fAn) | wc -l` -eq 0 ]] || ( git --no-pager diff; git add -fAn; echo Please run 'go mod tidy' and commit again ; exit 1 )"

  golangci-lint:
    executor: golangci
       
    steps:
     - checkout
     - run: make golangci-lint

workflows:
    version: 2
    default:
      jobs:
        - build
        - test
        - check_repo_consistency
        - crossbuild
        - golangci-lint
      
    release:
      jobs:
        - build:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        - test:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        - check_repo_consistency:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        - crossbuild:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        - golangci-lint:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        - hold:
            type:
              approval
            requires:
              - build
              - test
              - check_repo_consistency
              - crossbuild
              - golangci-lint
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      
        - publish_release:
            requires:
              - hold
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      
